AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: boardgames-discord-bot

Globals:
  Function:
    Timeout: 3
    Tracing: Active
    LoggingConfig:
      LogFormat: JSON
  Api:
    TracingEnabled: true

Resources:
  SendMassage:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: send-message/
      Handler: app.lambdaHandler
      Runtime: nodejs22.x
      Environment:
        Variables:
          DISCORD_BOT_TOKEN: ""
      Architectures:
        - x86_64
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        SendMassage:
          Type: Api
          Properties:
            Path: /messages
            Method: post
  # DiscordBotFunctionRole:
  #   Type: AWS::IAM::Role
  #   Properties:
  #     AssumeRolePolicyDocument:
  #       Version: '2012-10-17'
  #       Statement:
  #         - Effect: Allow
  #           Principal:
  #             Service: lambda.amazonaws.com
  #           Action: sts:AssumeRole
  #     ManagedPolicyArns:
  #       - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
  #     Policies:
  #       - PolicyName: InvokeSendMassagePolicy
  #         PolicyDocument:
  #           Version: '2012-10-17'
  #           Statement:
  #             - Effect: Allow
  #               Action: lambda:InvokeFunction
  #               Resource: !GetAtt SendMassage.Arn
  DiscordBotFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello-world/
      Handler: app.lambdaHandler
      Runtime: nodejs22.x
      Environment:
        Variables:
          PUBLIC_KEY: ""
      Architectures:
        - x86_64
      # Role: !GetAtt DiscordBotFunctionRole.Arn
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            - Effect: Allow
              Action: lambda:InvokeFunction
              Resource: !GetAtt SendMassage.Arn
      Events:
        DiscordWebhook:
          Type: Api
          Properties:
            Path: /interactions
            Method: post


  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name: !Sub ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0

  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName: !Ref ApplicationResourceGroup
      AutoConfigurationEnabled: 'true'

Outputs:
  DiscordBotApi:
    Description: API Gateway endpoint URL for Prod stage for Hello World function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com"
  DiscordBotFunction:
    Description: Hello World Lambda Function ARN
    Value: !GetAtt DiscordBotFunction.Arn
  DiscordBotFunctionIamRole:
    Description: Implicit IAM Role created for Hello World function
    Value: !GetAtt DiscordBotFunctionRole.Arn
  ApiGatewayInvokeURL:
    Description: API Gateway endpoint URL for Discord bot
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com"